[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[build]
  publish = "public"
  command = "yarn run build"

[[redirects]]
  from = "build"
  to = "https://api.netlify.com/api/v1/badges/4f030fdc-e791-4d2e-8c5f-d69752304535/deploy-status"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/nbilleau"

[[redirects]]
  from = "/instagram"
  to = "https://instagram.com/nathanbilleau"

[[redirects]]
  from = "/github"
  to = "https://github.com/nathanbilleau"

[[redirects]]
  from = "/twitch"
  to = "https://www.twitch.tv/nathanbilleau"

[[redirects]]
  from = "/spotify"
  to = "https://open.spotify.com/user/k3bulby2da3bx6vpb4yrl69ee?si=HPNzSQJnRvmrco1Xx8AB4Q"

[[redirects]]
  from = "/tiktok"
  to = "https://vm.tiktok.com/ZSgKGvg4/"

[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCC8p91cfvnn28Hkm9ks2C6A?view_as=subscriber"