backend:
  name: git-gateway
  branch: master

media_folder: "content/images"
public_folder: "public/static"

collections:
  - name: "works" # Used in routes, e.g., /admin/collections/blog
    label: "Réalisations" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Images"
        name: "pics"
        widget: "object"
        field:
          - name: Image
            label: image
            widget: image
      - {label: "Body", name: "body", widget: "markdown"}
